#!/usr/bin/env node
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import { spawnSync } from "node:child_process";

const uiDir = "src/ui";
const indexPath = join(uiDir, "index.ts");
const installedPath = "src/installed-components.ts";

const files = readdirSync(uiDir)
  .filter((file) => file.endsWith(".tsx") && file !== "index.ts")
  .sort();

const barrelExports = files.map((file) => {
  const stem = basename(file, ".tsx");
  return `export * from "./${stem}";`;
});

writeFileSync(
  indexPath,
  `// Auto-generated by scripts/sync-ui.mjs — do not edit manually.\n${barrelExports.join("\n")}\n`,
);

const installedNames = new Set(["Fragment", "React"]);

function collectExports(source) {
  const blockMatch = source.match(/export\s*\{([^}]+)\}/g) ?? [];
  for (const block of blockMatch) {
    const names = block
      .replace(/^export\s*\{/, "")
      .replace(/\}$/, "")
      .split(",")
      .map((part) => part.trim())
      .filter(Boolean);

    for (const entry of names) {
      const aliasMatch = entry.match(/^\w+\s+as\s+(\w+)$/);
      const fnMatch = entry.match(/^function\s+(\w+)/);
      const constMatch = entry.match(/^(?:const|let|var)\s+(\w+)/);
      const plainMatch = entry.match(/^(\w+)$/);
      const name = aliasMatch?.[1] ?? fnMatch?.[1] ?? constMatch?.[1] ?? plainMatch?.[1];
      if (name && /^[A-Z]/.test(name)) installedNames.add(name);
    }
  }

  const fnExports = source.matchAll(/export\s+function\s+([A-Z]\w*)/g);
  for (const match of fnExports) installedNames.add(match[1]);

  const constExports = source.matchAll(/export\s+const\s+([A-Z]\w*)/g);
  for (const match of constExports) installedNames.add(match[1]);
}

for (const file of files) {
  const path = join(uiDir, file);
  const source = readFileSync(path, "utf8");
  const updated = source
    .replaceAll('from "@/lib/utils"', 'from "../lib/utils"')
    .replaceAll('from "@/hooks/use-mobile"', 'from "../hooks/use-mobile"')
    .replaceAll('from "@/components/ui/', 'from "./')
    .replaceAll('from "@/ui/', 'from "./');
  if (updated !== source) {
    writeFileSync(path, updated);
    console.log(`fixed imports in ${path}`);
  }
  collectExports(updated);
}

const sorted = [...installedNames].sort();
writeFileSync(
  installedPath,
  `// Auto-generated by scripts/sync-ui.mjs — do not edit manually.\nexport const INSTALLED_SHADCN_COMPONENTS: string[] = ${JSON.stringify(sorted, null, 2)};\n`,
);

console.log(`synced ${files.length} ui components -> ${indexPath}`);
console.log(`indexed ${sorted.length} installed component exports -> ${installedPath}`);

const lint = spawnSync("pnpm", ["lint"], { stdio: "inherit", shell: true });
if (lint.status !== 0) {
  process.exit(lint.status ?? 1);
}
